// Maps the exact country strings used in the wine dataset to the ISO 3166-1
// alpha-2 codes used as path ids in lib/world-map-paths.ts.
export const COUNTRY_TO_ISO: Record<string, string> = {
  Argentina: "ar",
  Armenia: "am",
  Australia: "au",
  Austria: "at",
  "Bosnia and Herzegovina": "ba",
  Brazil: "br",
  Bulgaria: "bg",
  Canada: "ca",
  Chile: "cl",
  China: "cn",
  Croatia: "hr",
  Cyprus: "cy",
  "Czech Republic": "cz",
  England: "gb",
  France: "fr",
  Georgia: "ge",
  Germany: "de",
  Greece: "gr",
  Hungary: "hu",
  India: "in",
  Israel: "il",
  Italy: "it",
  Lebanon: "lb",
  Luxembourg: "lu",
  Macedonia: "mk",
  Mexico: "mx",
  Moldova: "md",
  Morocco: "ma",
  "New Zealand": "nz",
  Peru: "pe",
  Portugal: "pt",
  Romania: "ro",
  Serbia: "rs",
  Slovakia: "sk",
  Slovenia: "si",
  "South Africa": "za",
  Spain: "es",
  Switzerland: "ch",
  Turkey: "tr",
  US: "us",
  Ukraine: "ua",
  Uruguay: "uy",
}
