export const COUNTRY_FLAGS: Record<string, string> = {
  Argentina: "🇦🇷",
  Armenia: "🇦🇲",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  "Bosnia and Herzegovina": "🇧🇦",
  Brazil: "🇧🇷",
  Bulgaria: "🇧🇬",
  Canada: "🇨🇦",
  Chile: "🇨🇱",
  China: "🇨🇳",
  Croatia: "🇭🇷",
  Cyprus: "🇨🇾",
  "Czech Republic": "🇨🇿",
  England: "🇬🇧",
  France: "🇫🇷",
  Georgia: "🇬🇪",
  Germany: "🇩🇪",
  Greece: "🇬🇷",
  Hungary: "🇭🇺",
  India: "🇮🇳",
  Israel: "🇮🇱",
  Italy: "🇮🇹",
  Lebanon: "🇱🇧",
  Luxembourg: "🇱🇺",
  Macedonia: "🇲🇰",
  Mexico: "🇲🇽",
  Moldova: "🇲🇩",
  Morocco: "🇲🇦",
  "New Zealand": "🇳🇿",
  Peru: "🇵🇪",
  Portugal: "🇵🇹",
  Romania: "🇷🇴",
  Serbia: "🇷🇸",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  "South Africa": "🇿🇦",
  Spain: "🇪🇸",
  Switzerland: "🇨🇭",
  Turkey: "🇹🇷",
  US: "🇺🇸",
  Ukraine: "🇺🇦",
  Uruguay: "🇺🇾",
}

export function getCountryFlag(country: string): string {
  return COUNTRY_FLAGS[country] || "🍇"
}
